# Generated by Django 3.0.7 on 2020-06-14 10:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bendahara', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notaitem',
            name='nota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bendahara.Nota'),
        ),
        migrations.AlterField(
            model_name='toko',
            name='nama_toko',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(1, 'nama_toko cannot be blank')]),
        ),
    ]
