# Generated by Django 3.0.7 on 2020-06-24 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bendahara', '0002_auto_20200614_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='BukuPraktikum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_buku', models.CharField(max_length=50)),
                ('tanggal_cetak_buku', models.DateField()),
                ('harga_beli_buku', models.IntegerField()),
                ('harga_jual_buku', models.IntegerField()),
                ('stok_buku', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PenjualanBuku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_penjualan_buku', models.DateField()),
                ('lab_penjualan_buku', models.CharField(max_length=5)),
                ('jumlah_penjualan_buku', models.PositiveSmallIntegerField()),
                ('terima_uang_penjualan_buku', models.IntegerField()),
                ('confirmed_uang_penjualan_buku', models.BooleanField(default=False)),
                ('buku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bendahara.BukuPraktikum')),
            ],
        ),
    ]
