# Generated by Django 3.0.7 on 2020-06-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bendahara', '0003_bukupraktikum_penjualanbuku'),
    ]

    operations = [
        migrations.AddField(
            model_name='bukupraktikum',
            name='jurusan_buku',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
    ]
