# Generated by Django 3.0.7 on 2020-07-02 06:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bendahara', '0004_bukupraktikum_jurusan_buku'),
    ]

    operations = [
        migrations.AddField(
            model_name='barang',
            name='tanggal_kembali',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='barang',
            name='user_konfirmasi_kembali',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PeminjamanBarang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_peminjaman', models.DateField(default=datetime.datetime(2020, 7, 2, 6, 34, 2, 286654, tzinfo=utc))),
                ('nama_peminjam', models.CharField(max_length=50)),
                ('user_meminjamkan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='barang',
            name='peminjaman_barang',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bendahara.PeminjamanBarang'),
            preserve_default=False,
        ),
    ]
