# Generated by Django 3.0.7 on 2020-07-02 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bendahara', '0005_auto_20200702_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peminjamanbarang',
            name='tanggal_peminjaman',
            field=models.DateField(auto_now_add=True),
        ),
    ]
