# Generated by Django 3.0.7 on 2020-07-02 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bendahara', '0007_auto_20200702_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang',
            name='peminjaman_barang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barangs', to='bendahara.PeminjamanBarang'),
        ),
        migrations.AlterField(
            model_name='barang',
            name='tanggal_kembali',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='barang',
            name='user_konfirmasi_kembali',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
